version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.4
    commands:
      - echo "Installing dependencies..."
      - composer install
  build:
    commands:
      - echo "Running PHPUnit tests..."
      - phpunit
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y arachni

    - arachni https://git-codecommit.us-east-1.amazonaws.com/v1/repos/Proyecto_Final_Final --report-save-path=arachni_report.afr
